//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18033
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class X {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal X() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.X", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Champion 的本地化字符串。
        /// </summary>
        internal static string Enum_BuyerPersonas_Champion {
            get {
                return ResourceManager.GetString("Enum_BuyerPersonas_Champion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coach 的本地化字符串。
        /// </summary>
        internal static string Enum_BuyerPersonas_Coach {
            get {
                return ResourceManager.GetString("Enum_BuyerPersonas_Coach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Economic Buyer 的本地化字符串。
        /// </summary>
        internal static string Enum_BuyerPersonas_EconomicBuyer {
            get {
                return ResourceManager.GetString("Enum_BuyerPersonas_EconomicBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FOX 的本地化字符串。
        /// </summary>
        internal static string Enum_BuyerPersonas_FOX {
            get {
                return ResourceManager.GetString("Enum_BuyerPersonas_FOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未指定 的本地化字符串。
        /// </summary>
        internal static string Enum_BuyerPersonas_None {
            get {
                return ResourceManager.GetString("Enum_BuyerPersonas_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Technical Buyer 的本地化字符串。
        /// </summary>
        internal static string Enum_BuyerPersonas_TechnicalBuyer {
            get {
                return ResourceManager.GetString("Enum_BuyerPersonas_TechnicalBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Buyer 的本地化字符串。
        /// </summary>
        internal static string Enum_BuyerPersonas_UserBuyer {
            get {
                return ResourceManager.GetString("Enum_BuyerPersonas_UserBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 决策者 的本地化字符串。
        /// </summary>
        internal static string Enum_BuyerTypes_Buyer {
            get {
                return ResourceManager.GetString("Enum_BuyerTypes_Buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非决策者 的本地化字符串。
        /// </summary>
        internal static string Enum_BuyerTypes_NotBuyer {
            get {
                return ResourceManager.GetString("Enum_BuyerTypes_NotBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法判断 的本地化字符串。
        /// </summary>
        internal static string Enum_BuyerTypes_Unknown {
            get {
                return ResourceManager.GetString("Enum_BuyerTypes_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批 的本地化字符串。
        /// </summary>
        internal static string Enum_CRUD_Check {
            get {
                return ResourceManager.GetString("Enum_CRUD_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        internal static string Enum_CRUD_Create {
            get {
                return ResourceManager.GetString("Enum_CRUD_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Enum_CRUD_Delete {
            get {
                return ResourceManager.GetString("Enum_CRUD_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 的本地化字符串。
        /// </summary>
        internal static string Enum_CRUD_Read {
            get {
                return ResourceManager.GetString("Enum_CRUD_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Enum_CRUD_Update {
            get {
                return ResourceManager.GetString("Enum_CRUD_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户 的本地化字符串。
        /// </summary>
        internal static string Enum_CustomerTyps_Customer {
            get {
                return ResourceManager.GetString("Enum_CustomerTyps_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合作伙伴 的本地化字符串。
        /// </summary>
        internal static string Enum_CustomerTyps_Partner {
            get {
                return ResourceManager.GetString("Enum_CustomerTyps_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商 的本地化字符串。
        /// </summary>
        internal static string Enum_CustomerTyps_Supplier {
            get {
                return ResourceManager.GetString("Enum_CustomerTyps_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存档 的本地化字符串。
        /// </summary>
        internal static string Enum_OrderStatus_Archived {
            get {
                return ResourceManager.GetString("Enum_OrderStatus_Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已审批 的本地化字符串。
        /// </summary>
        internal static string Enum_OrderStatus_Checked {
            get {
                return ResourceManager.GetString("Enum_OrderStatus_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已结束 的本地化字符串。
        /// </summary>
        internal static string Enum_OrderStatus_Finished {
            get {
                return ResourceManager.GetString("Enum_OrderStatus_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已入库 的本地化字符串。
        /// </summary>
        internal static string Enum_OrderStatus_Inned {
            get {
                return ResourceManager.GetString("Enum_OrderStatus_Inned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已部分入库 的本地化字符串。
        /// </summary>
        internal static string Enum_OrderStatus_InnedSome {
            get {
                return ResourceManager.GetString("Enum_OrderStatus_InnedSome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已下单 的本地化字符串。
        /// </summary>
        internal static string Enum_OrderStatus_Ordered {
            get {
                return ResourceManager.GetString("Enum_OrderStatus_Ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已出库 的本地化字符串。
        /// </summary>
        internal static string Enum_OrderStatus_Outted {
            get {
                return ResourceManager.GetString("Enum_OrderStatus_Outted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已部分出库 的本地化字符串。
        /// </summary>
        internal static string Enum_OrderStatus_OuttedSome {
            get {
                return ResourceManager.GetString("Enum_OrderStatus_OuttedSome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已支付 的本地化字符串。
        /// </summary>
        internal static string Enum_OrderStatus_Paid {
            get {
                return ResourceManager.GetString("Enum_OrderStatus_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已部分支付 的本地化字符串。
        /// </summary>
        internal static string Enum_OrderStatus_PaidSome {
            get {
                return ResourceManager.GetString("Enum_OrderStatus_PaidSome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没可能 的本地化字符串。
        /// </summary>
        internal static string Enum_SuccessRatioes_SR00 {
            get {
                return ResourceManager.GetString("Enum_SuccessRatioes_SR00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20%机会 的本地化字符串。
        /// </summary>
        internal static string Enum_SuccessRatioes_SR20 {
            get {
                return ResourceManager.GetString("Enum_SuccessRatioes_SR20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 40%机会 的本地化字符串。
        /// </summary>
        internal static string Enum_SuccessRatioes_SR40 {
            get {
                return ResourceManager.GetString("Enum_SuccessRatioes_SR40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 80%机会 的本地化字符串。
        /// </summary>
        internal static string Enum_SuccessRatioes_SR80 {
            get {
                return ResourceManager.GetString("Enum_SuccessRatioes_SR80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 租户管理员 的本地化字符串。
        /// </summary>
        internal static string Enum_UserTypes_HostAdministrator {
            get {
                return ResourceManager.GetString("Enum_UserTypes_HostAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通用户 的本地化字符串。
        /// </summary>
        internal static string Enum_UserTypes_Normal {
            get {
                return ResourceManager.GetString("Enum_UserTypes_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理员 的本地化字符串。
        /// </summary>
        internal static string Enum_UserTypes_SystemAdministrator {
            get {
                return ResourceManager.GetString("Enum_UserTypes_SystemAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string Enum_VisitWays_Email {
            get {
                return ResourceManager.GetString("Enum_VisitWays_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 即时通讯 的本地化字符串。
        /// </summary>
        internal static string Enum_VisitWays_IM {
            get {
                return ResourceManager.GetString("Enum_VisitWays_IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string Enum_VisitWays_Tel {
            get {
                return ResourceManager.GetString("Enum_VisitWays_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上门拜访 的本地化字符串。
        /// </summary>
        internal static string Enum_VisitWays_ToDoor {
            get {
                return ResourceManager.GetString("Enum_VisitWays_ToDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已有网站 的本地化字符串。
        /// </summary>
        internal static string Enum_WebSiteStatus_HadSite {
            get {
                return ResourceManager.GetString("Enum_WebSiteStatus_HadSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可能改版 的本地化字符串。
        /// </summary>
        internal static string Enum_WebSiteStatus_MaybeBetter {
            get {
                return ResourceManager.GetString("Enum_WebSiteStatus_MaybeBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有网站 的本地化字符串。
        /// </summary>
        internal static string Enum_WebSiteStatus_NoSite {
            get {
                return ResourceManager.GetString("Enum_WebSiteStatus_NoSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台网站 的本地化字符串。
        /// </summary>
        internal static string Enum_WebSiteStatus_PlatformSite {
            get {
                return ResourceManager.GetString("Enum_WebSiteStatus_PlatformSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稍后联络 的本地化字符串。
        /// </summary>
        internal static string Enum_Wishs_ContactLater {
            get {
                return ResourceManager.GetString("Enum_Wishs_ContactLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 约定下次拜访 的本地化字符串。
        /// </summary>
        internal static string Enum_Wishs_DateToDoor {
            get {
                return ResourceManager.GetString("Enum_Wishs_DateToDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 约定签约 的本地化字符串。
        /// </summary>
        internal static string Enum_Wishs_DateToOrder {
            get {
                return ResourceManager.GetString("Enum_Wishs_DateToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有意向 的本地化字符串。
        /// </summary>
        internal static string Enum_Wishs_Maybe {
            get {
                return ResourceManager.GetString("Enum_Wishs_Maybe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂不考虑 的本地化字符串。
        /// </summary>
        internal static string Enum_Wishs_NotConsider {
            get {
                return ResourceManager.GetString("Enum_Wishs_NotConsider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负责人不在 的本地化字符串。
        /// </summary>
        internal static string Enum_Wishs_NotPresent {
            get {
                return ResourceManager.GetString("Enum_Wishs_NotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经签约 的本地化字符串。
        /// </summary>
        internal static string Enum_Wishs_Ordered {
            get {
                return ResourceManager.GetString("Enum_Wishs_Ordered", resourceCulture);
            }
        }
    }
}
